---
abstract: 'Validate subroutine parameters.'
author:
  - 'Sergio Iglesias <sergioxz@cpan.org>'
build_requires:
  Test::Exception: '0'
  Types::Standard: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Attribute-Validate
provides:
  Attribute::Validate:
    file: lib/Attribute/Validate.pm
    version: v0.0.8
requires:
  Attribute::Handlers: '0'
  Carp: '0'
  Carp::Always: '0'
  Type::Params: '2.008003'
  perl: v5.16.3
resources:
  bugtracker: https://github.com/sergiotarxz/Perl-Attribute-Validate/issues
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://github.com/sergiotarxz/Perl-Attribute-Validate
version: v0.0.8
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
